# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7z020clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/Xilink/SoC/GEMINI/Final/Final.cache/wt [current_project]
set_property parent.project_path D:/Xilink/SoC/GEMINI/Final/Final.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/Xilink/SoC/GEMINI/Final/Final.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  D:/Xilink/SoC/GEMINI/Final/Final.srcs/sources_1/new/alu.v
  D:/Xilink/SoC/GEMINI/Final/Final.srcs/sources_1/new/control_unit.v
  D:/Xilink/SoC/GEMINI/Final/Final.srcs/sources_1/new/data_mem.v
  D:/Xilink/SoC/GEMINI/Final/Final.srcs/sources_1/new/forwarding_unit.v
  D:/Xilink/SoC/GEMINI/Final/Final.srcs/sources_1/new/hazard_unit.v
  D:/Xilink/SoC/GEMINI/Final/Final.srcs/sources_1/new/imm_gen.v
  D:/Xilink/SoC/GEMINI/Final/Final.srcs/sources_1/new/instr_mem.v
  D:/Xilink/SoC/GEMINI/Final/Final.srcs/sources_1/new/pc_reg.v
  D:/Xilink/SoC/GEMINI/Final/Final.srcs/sources_1/new/reg_file.v
  D:/Xilink/SoC/GEMINI/Final/Final.srcs/sources_1/new/rv32i_pipeline.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/Xilink/SoC/GEMINI/Final/Final.srcs/constrs_1/new/rv32i_constraints.xdc
set_property used_in_implementation false [get_files D:/Xilink/SoC/GEMINI/Final/Final.srcs/constrs_1/new/rv32i_constraints.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top rv32i_pipeline -part xc7z020clg400-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef rv32i_pipeline.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file rv32i_pipeline_utilization_synth.rpt -pb rv32i_pipeline_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
